################# Russian language ################
[ru]
languageName = "Русский"
languageCode = "ru-RU"
contentDir = "content/russian"
weight = 1

################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 2
